version: '3.6'
services:
  iris:
    build: 
      context: .
      
    restart: always
    ports: 
      - 52774:52773
    volumes:
      - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./:/home/irisowner/zpm/