version: '3'
services:
  iris:
    build: .
    restart: always
    environment:
      - TEST_REGISTRY=http://registry:52773/registry/
      - TEST_REGISTRY_USER=admin
      - TEST_REGISTRY_PASSWORD=SYS
    ports: 
      - 52774:52773
    volumes:
      - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./:/home/irisowner/zpm/
    command:
      - -a 
      - iris session iris -U%SYS '##class(Security.Users).UnExpireUserPasswords("*")'
  registry:
    image: intersystemsdc/iris-community:preview
    restart: always
    ports: 
      - 52775:52773
    environment:
      - IRISPASSWORD=SYS
      - IRISUSERNAME=admin
      - IRISNAMESPACE=REGISTRY
    volumes:
      - ./setup-registry.sh:/docker-entrypoint-initdb.d/setup-registry.sh
