version: '3'
services:
  iris:
    build: 
      context: .
      
    restart: always
    ports: 
      - 52774:52773
    command:
      - -a
      - iris session iris -U%SYS '##class(Security.Users).UnExpireUserPasswords("*")'
    volumes:
      - ./:/home/irisowner/ipm/
      - ~/iris.key:/usr/irissys/mgr/iris.key
