name: Changelog Check

on:
  pull_request:
    branches:
      - main
      - v0.9.x
      - v0.10.x

jobs:
  check_changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with: 
        fetch-depth: 0

    - name: Check for updated CHANGELOG.md
      run: |
        # actions/checkout@v4 will merge the feature branch into target branch, hence `HEAD` is not the feature head
        # While it is probably okay to diff this HEAD against the target branch, we explicitly compare the feature head against the target for readability.
        if git diff --name-only ${{ github.event.pull_request.head.sha }}...origin/${{ github.event.pull_request.base.ref }} | grep -q 'CHANGELOG.md'; then
          echo "CHANGELOG.md has been updated."
        else
          echo "CHANGELOG.md has not been updated."
          exit 1
        fi