name: Test all packages
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: |
        minVersions=3
        matrix=`curl https://pm.community.intersystems.com/packages/-/all  | jq 'reduce .[] as $item ([]; if $item.allVersions | length >= ${minVersions} then . + [$item.name] end)' | tr -d '\n\t\r '`
        echo $matrix
        echo "matrix=${matrix}" >> "$GITHUB_OUTPUT"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - run: echo test